# Generated by Django 2.2 on 2020-04-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
