# Generated by Django 2.2 on 2020-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200426_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='name',
        ),
    ]
