# Generated by Django 2.2 on 2020-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200426_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
